[provider]
cluster = "localnet"  # Use localnet for testing, change to mainnet-beta for production
wallet = "~/.config/solana/id.json"  # Path to your Solana wallet

[programs.localnet]
voting_system = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"  # Replace with your program ID

[scripts]
test = "anchor test --skip-local-validator"  # Test command configuration

[test]
genesis = [
  { address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", program = "token.so" }
]
[test.validator]
url = "https://api.devnet.solana.com"  # Test validator RPC URL
cluster = "localnet"
bind_address = "0.0.0.0"
dynamic_port_range = "8000-8010"
limit_load = false
account_dir = "test-ledger"
reset = true  # Clean ledger on each test run

# Enable necessary features and sysvars
[test.validator.clone]
sysvar-rent = true
sysvar-clock = true
sysvar-stake-history = true
sysvar-rewards = true

# Clone required programs
[test.validator.clone.programs]
spl-token = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

# Test validator configuration flags
[test.validator.extra_args]
--rpc-port = 8899
--enable-cpi-and-log-storage = true
--quiet = false
--account-index = true
--no-os-network-limits-test = true
--reset = true
--limit-ledger-size = "100000000"
--rpc-pubsub-enable-block-subscription = true
--log = "solana=info"
